apiVersion: v1
kind: Service
metadata:
  name: pighand-notify
  labels:
    app: pighand-notify
    service: pighand-notify
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 19092
      targetPort: 9092
    - name: grpc
      port: 18888
      targetPort: 18888
  selector:
    app: pighand-notify

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-pay-v1
  labels:
    app: micro-pay
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micro-pay
      version: v1
  template:
    metadata:
      labels:
        app: micro-pay
        version: v1
    spec:
      containers:
        - name: micro-pay
          image: 10.211.55.2:8080/micro-service/micro-pay:1.0-SNAPSHOT
          imagePullPolicy: Always
          tty: true
          ports:
            - name: http
              protocol: TCP
              containerPort: 19092
            #指定服务gRPC端口
            - name: grpc
              protocol: TCP
              containerPort: 18888